### ISSUE TITLE
Cannot get it work

### ISSUE THREAD

**Issue by qinsoon** [eladchen/protected-workflows#2]
I am trying to use this Github app. My first attempt was the following config - I was just trying to prevent unlisted users from changing workflows:
```
events:
  pull_request: &config
    - trustAnyone: true
      paths:
        disallowed:
          - ".github/**"
          - ".github/protected-workflows.yml"
    - trustedUserNames:
        - "aaa"
        - "bbb"
        - "ccc"
  
  pull_request_target: *config
  push: *config

# 'anyEvent' value is a rule, and will be used when an event specific configuration is not set.
# It is automatically added in case it was not explictly set and it does not supports the 'paths' property.
anyEvent:
  trustAnyone: false
  trustCollaborators: false
  trustedUserNames: []
```
I listed myself in `trustedUserNames`. However, when I submitted a PR for this workflow config, my CI workflow was trigger but got cancelled. 

Then I changed the `trustedUserNames` part to `trustOrgMembers: true` (I am an org member). The workflow was not triggered at all. 

I cannot find a way to debug, as I do not have any message/output from the app.

**Comment by qinsoon** [comment]
I also noticed that after installing the Github app, all existing workflows will be cancelled even there is no configuration `protected-workflow.yml`.

**Comment by eladchen** [comment]
> I also noticed that after installing the Github app, all existing workflows will be cancelled even there is no configuration `protected-workflow.yml`.

That is expected. If a config file does not exists or some properties of "anyEvent" are not set
the app uses the following as defaults:

```yml
anyEvent:
  trustAnyone: false
  trustCollaborators: false
  trustedUserNames: []
```

There is actually a description of this:
> It is automatically added in case it was not explicitly set and it does not support the 'paths' property.

Do you think the above description should be given more focus?
