### ISSUE TITLE
Can't get this to run

### ISSUE THREAD

**Issue by a-monteiro** [eladchen/protected-workflows#5]
Hi,

It seems I can't get this to run while testing on a private repo using a very simple configuration:

```
events:
  pull_request: &config

    - trustAnyone: true
      paths:
        disallowed:
          - ".github/**"
          - ".github/protected-workflows.yml"

  pull_request_target: *config

  push: *config

anyEvent:
  trustAnyone: false
  trustCollaborators: false
  #trustOrgMembers: true
  trustedUserNames: []
```

Am I doing something wrong or this App isn't working anymore? I don't know how I can troubleshoot this.
